"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { z } from "zod";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace"; import { createClient } from "@/lib/supabase/server";
import { crousLogInputSchema, crousPeriodInputSchema, type CrousLogInput } from "../schemas/crous-hours.schema";
import { parisLocalToIso } from "../services/crous-hours.calculations";
export type CrousActionState = { message?: string; fieldErrors?: Record<string, string[] | undefined>; overlaps?: Array<{ id: string; starts_at: string; ends_at: string }>; submitted?: CrousLogInput };
const periodValues = (formData: FormData) => ({ mission_id: formData.get("mission_id"), label: formData.get("label"), starts_on: formData.get("starts_on"), ends_on: formData.get("ends_on"), target_minutes: formData.get("target_minutes") });
const logValues = (formData: FormData) => ({ period_id: formData.get("period_id"), starts_at: parisLocalToIso(String(formData.get("starts_at"))), ends_at: parisLocalToIso(String(formData.get("ends_at"))), credited_minutes: formData.get("credited_minutes"), adjustment_reason: formData.get("adjustment_reason"), notes: formData.get("notes") });
async function validCrousMission(workspaceId: string, missionId: string) { const supabase = await createClient(); const { data, error } = await supabase.from("missions").select("id, organization:organizations!inner(type)").eq("workspace_id", workspaceId).eq("id", missionId).eq("organization.type", "crous").is("archived_at", null).maybeSingle(); return !error && Boolean(data); }
export async function createCrousPeriodAction(_state: CrousActionState, formData: FormData): Promise<CrousActionState> { const parsed = crousPeriodInputSchema.safeParse(periodValues(formData)); if (!parsed.success) return { message: "Corrigez les champs indiqués.", fieldErrors: parsed.error.flatten().fieldErrors }; const workspace = await getActiveWorkspace(); if (!await validCrousMission(workspace.id, parsed.data.mission_id)) return { message: "Sélectionnez une mission active liée à une organisation CROUS." }; const supabase = await createClient(); const { data, error } = await supabase.from("crous_hour_periods").insert({ workspace_id: workspace.id, ...parsed.data }).select("id").single(); if (error || !data) return { message: error?.code === "23505" ? "Une période active identique existe déjà." : "La période n’a pas pu être enregistrée." }; revalidatePath("/crous-hours"); redirect(`/crous-hours/${data.id}`); }
export async function updateCrousPeriodAction(periodId: string, _state: CrousActionState, formData: FormData): Promise<CrousActionState> { const id = z.uuid().safeParse(periodId); const parsed = crousPeriodInputSchema.safeParse(periodValues(formData)); if (!id.success || !parsed.success) return { message: "Corrigez les champs indiqués.", fieldErrors: parsed.success ? undefined : parsed.error.flatten().fieldErrors }; const workspace = await getActiveWorkspace(); if (!await validCrousMission(workspace.id, parsed.data.mission_id)) return { message: "Sélectionnez une mission CROUS active." }; const supabase = await createClient(); const { data, error } = await supabase.from("crous_hour_periods").update(parsed.data).eq("workspace_id", workspace.id).eq("id", id.data).select("id").maybeSingle(); if (error || !data) return { message: "La période n’a pas pu être enregistrée." }; revalidatePath("/crous-hours"); revalidatePath(`/crous-hours/${id.data}`); redirect(`/crous-hours/${id.data}`); }
async function saveLog(logId: string | null, state: CrousActionState, formData: FormData): Promise<CrousActionState> { const parsed = crousLogInputSchema.safeParse(logValues(formData)); if (!parsed.success) return { message: "Corrigez les champs indiqués.", fieldErrors: parsed.error.flatten().fieldErrors }; const workspace = await getActiveWorkspace(); const supabase = await createClient(); const period = await supabase.from("crous_hour_periods").select("id").eq("workspace_id", workspace.id).eq("id", parsed.data.period_id).is("archived_at", null).maybeSingle(); if (period.error || !period.data) return { message: "Cette période est indisponible." }; const startsAt = new Date(parsed.data.starts_at).toISOString(); const endsAt = new Date(parsed.data.ends_at).toISOString(); const overlapQuery = supabase.from("crous_work_logs").select("id, starts_at, ends_at").eq("workspace_id", workspace.id).neq("id", logId ?? "00000000-0000-0000-0000-000000000000").is("archived_at", null).lt("starts_at", endsAt).gt("ends_at", startsAt).limit(5); const overlapResult = await overlapQuery; if (overlapResult.error) return { message: "Le contrôle des chevauchements a échoué." }; if (overlapResult.data.length && formData.get("confirm_overlap") !== "yes") return { message: "Une ou plusieurs interventions se chevauchent.", overlaps: overlapResult.data, submitted: parsed.data };
  const payload = { workspace_id: workspace.id, period_id: parsed.data.period_id, starts_at: startsAt, ends_at: endsAt, credited_minutes: parsed.data.credited_minutes, adjustment_reason: parsed.data.adjustment_reason, notes: parsed.data.notes }; const result = logId ? await supabase.from("crous_work_logs").update(payload).eq("workspace_id", workspace.id).eq("id", logId).select("id").maybeSingle() : await supabase.from("crous_work_logs").insert(payload).select("id").single(); if (result.error || !result.data) return { message: result.error?.code === "23514" ? "Vérifiez la durée, la période et la justification." : "L’intervention n’a pas pu être enregistrée." }; revalidatePath(`/crous-hours/${parsed.data.period_id}`); redirect(`/crous-hours/${parsed.data.period_id}`); }
export async function createCrousLogAction(state: CrousActionState, formData: FormData) { return saveLog(null, state, formData); }
export async function updateCrousLogAction(logId: string, state: CrousActionState, formData: FormData) { return saveLog(z.uuid().parse(logId), state, formData); }
export async function archiveCrousPeriodAction(periodId: string) { const id = z.uuid().parse(periodId); const workspace = await getActiveWorkspace(); const supabase = await createClient(); const { data, error } = await supabase.from("crous_hour_periods").update({ archived_at: new Date().toISOString() }).eq("workspace_id", workspace.id).eq("id", id).is("archived_at", null).select("id").maybeSingle(); if (error || !data) throw new Error("Unable to archive CROUS period."); revalidatePath("/crous-hours"); redirect("/crous-hours?archive=archived"); }
export async function archiveCrousLogAction(logId: string, periodId: string) { const ids = z.object({ logId: z.uuid(), periodId: z.uuid() }).parse({ logId, periodId }); const workspace = await getActiveWorkspace(); const supabase = await createClient(); const { data, error } = await supabase.from("crous_work_logs").update({ archived_at: new Date().toISOString() }).eq("workspace_id", workspace.id).eq("id", ids.logId).eq("period_id", ids.periodId).select("id").maybeSingle(); if (error || !data) throw new Error("Unable to archive CROUS log."); revalidatePath(`/crous-hours/${ids.periodId}`); }
