import Link from "next/link";
import { notFound } from "next/navigation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace";
import { archiveMissionAction } from "@/modules/missions/actions/mission.actions";
import { missionStatusLabels } from "@/modules/missions/schemas/mission.schema";
import { getMission } from "@/modules/missions/services/mission.service";
import { TaskBoard } from "@/modules/tasks/components/task-board";
import { listTasks } from "@/modules/tasks/services/task.service";
export default async function MissionDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const workspace = await getActiveWorkspace(); const [mission, tasks] = await Promise.all([getMission(workspace.id, id), listTasks(workspace.id, { missionId: id })]); if (!mission) notFound(); const archive = archiveMissionAction.bind(null, id); return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-5xl space-y-6 px-4 py-7 outline-none sm:px-6 sm:py-9"><div><Link href="/missions" className="text-sm font-medium text-primary hover:underline">← Missions</Link><h1 className="mt-3 text-2xl font-semibold">{mission.title}</h1><p className="mt-1 text-sm text-muted-foreground">{mission.organization?.name} · {missionStatusLabels[mission.status]}</p></div><Card><CardHeader><CardTitle>Informations</CardTitle></CardHeader><CardContent>{mission.description ? <p className="whitespace-pre-wrap text-sm">{mission.description}</p> : <p className="text-sm text-muted-foreground">Aucune description.</p>}<p className="text-sm">Début : {mission.starts_on ?? "Non défini"} · Cible : {mission.target_ends_on ?? "Non définie"}</p></CardContent></Card><div className="flex flex-col gap-3 sm:flex-row"><Link href={`/missions/${id}/edit`} className={buttonVariants({ variant: "outline" })}>Modifier</Link>{!mission.archived_at ? <form action={archive}><Button type="submit" variant="destructive" className="w-full">Archiver</Button></form> : null}</div><section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Tâches</h2>{!mission.archived_at ? <Link href={`/tasks/new?mission=${id}`} className={buttonVariants({ size: "sm" })}>Nouvelle tâche</Link> : null}</div><TaskBoard tasks={tasks} /></section></main>; }
