import path from "node:path";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";
import { getTestSupabaseEnv } from "../helpers/test-env";

test("document metadata lifecycle, upload UI and accessible mobile layout", async ({ page }) => {
  const { url, publishableKey } = getTestSupabaseEnv();
  const client = createClient(url, publishableKey, { auth: { persistSession: false, autoRefreshToken: false } });
  const email = `e2e-documents-${Date.now()}-${crypto.randomUUID()}@example.test`;
  const password = `Local-only-${crypto.randomUUID()}!`;
  const signUp = await client.auth.signUp({ email, password });
  expect(signUp.error).toBeNull();
  if (!signUp.data.session) expect((await client.auth.signInWithPassword({ email, password })).error).toBeNull();
  const workspace = await client.rpc("bootstrap_personal_workspace");
  expect(workspace.error).toBeNull();
  const documentRow = await client.from("documents").insert({ workspace_id: workspace.data, name: "Synthetic Document E2E", category: "administrative", status: "valid", issued_on: "2026-09-01", expires_on: "2026-09-30" }).select("id").single();
  expect(documentRow.error).toBeNull();
  if (!documentRow.data) throw new Error("Synthetic document setup failed");
  const documentId = documentRow.data.id;
  const session = await client.from("document_upload_sessions").insert({ workspace_id: workspace.data, document_id: documentId, storage_bucket: "synthetic-private-bucket", storage_key: `${workspace.data}/${documentId}/${crypto.randomUUID()}.pdf`, original_file_name: "synthetic.pdf", expected_size: 1024, expected_mime: "application/pdf", state: "verifying", expires_at: new Date(Date.now() + 60_000).toISOString() }).select("id").single();
  expect(session.error).toBeNull();
  if (!session.data) throw new Error("Synthetic upload session setup failed");
  expect((await client.rpc("finalize_document_upload", { p_session_id: session.data.id, p_actual_size: 1024, p_sha256: "d".repeat(64), p_etag: "synthetic" })).error).toBeNull();

  await page.goto("/login");
  await page.getByLabel("Adresse e-mail").fill(email);
  await page.getByLabel("Mot de passe").fill(password);
  await page.getByRole("button", { name: "Se connecter" }).click();
  await expect(page.getByRole("heading", { name: "Personal Workspace" })).toBeVisible({ timeout: 15_000 });
  await page.goto("/documents");
  await expect(page.getByRole("link", { name: "Synthetic Document E2E" })).toBeVisible();
  await page.getByRole("link", { name: "Nouveau document" }).click();
  await expect(page.getByRole("heading", { name: "Nouveau document" })).toBeVisible();
  await expect(page.locator('input[type="file"]').first()).toBeAttached();
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.addScriptTag({ path: path.join(process.cwd(), "node_modules", "axe-core", "axe.min.js") });
  const serious = await page.evaluate(async () => (await (window as unknown as { axe: { run: (document: Document) => Promise<{ violations: Array<{ impact: string | null }> }> } }).axe.run(document)).violations.filter((item) => item.impact === "critical" || item.impact === "serious"));
  expect(serious).toEqual([]);
  await page.goto(`/documents/${documentId}`);
  await expect(page.getByRole("heading", { name: "Synthetic Document E2E" })).toBeVisible();
  await page.getByRole("link", { name: "Ajouter une version" }).click();
  await expect(page.getByRole("heading", { name: "Nouvelle version" })).toBeVisible();
  await page.goto(`/documents/${documentId}`);
  await page.getByRole("link", { name: "Modifier" }).click();
  await page.getByLabel("Nom").fill("Synthetic Document Updated");
  await page.getByRole("button", { name: "Enregistrer" }).click();
  await expect(page.getByRole("heading", { name: "Synthetic Document Updated" })).toBeVisible();
  await page.getByRole("button", { name: "Archiver" }).click();
  await expect(page).toHaveURL(/archive=archived/);
  await expect(page.getByRole("link", { name: "Synthetic Document Updated" })).toBeVisible();
});
