import Link from "next/link";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace";
import { listOrganizations } from "@/modules/organizations/services/list-organizations";
import { documentCategories, documentCategoryLabels, documentStatuses, documentStatusLabels } from "@/modules/documents/schemas/document.schema";
import { listDocuments } from "@/modules/documents/services/document.service";

export default async function DocumentsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams; const workspace = await getActiveWorkspace(); const value = (key: string) => typeof params[key] === "string" ? params[key] as string : undefined;
  const filters = { archive: value("archive") === "archived" ? "archived" : "active", organization: value("organization"), category: value("category"), status: value("status"), expiration: value("expiration") };
  const [documents, organizations] = await Promise.all([listDocuments(workspace.id, filters), listOrganizations(workspace.id)]);
  return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-6xl space-y-6 px-4 py-7 outline-none sm:px-6 sm:py-9"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Espace privé</p><h1 className="mt-1 text-2xl font-semibold">Documents</h1><p className="mt-1 text-sm text-muted-foreground">Versions privées, intégrité vérifiée et téléchargements temporaires.</p></div><Link href="/documents/new" className={buttonVariants()}>Nouveau document</Link></div>
  <Card><CardHeader><CardTitle>Filtres</CardTitle></CardHeader><CardContent><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Filter name="archive" label="Archivage" value={filters.archive} options={[{ value: "active", label: "Actifs" }, { value: "archived", label: "Archivés" }]} /><Filter name="organization" label="Organisation" value={filters.organization} options={organizations.map((item) => ({ value: item.id, label: item.name }))} all /><Filter name="category" label="Catégorie" value={filters.category} options={documentCategories.map((item) => ({ value: item, label: documentCategoryLabels[item] }))} all /><Filter name="status" label="Statut" value={filters.status} options={documentStatuses.map((item) => ({ value: item, label: documentStatusLabels[item] }))} all /><Filter name="expiration" label="Expiration" value={filters.expiration} options={[{ value: "expired", label: "Expirés" }, { value: "valid", label: "Non expirés" }, { value: "none", label: "Sans expiration" }]} all /><button className={buttonVariants({ variant: "outline" })}>Appliquer</button></form></CardContent></Card>
  {documents.length ? <ul className="grid gap-4 md:grid-cols-2">{documents.map((document) => <li key={document.id}><Card className="h-full"><CardHeader><CardTitle><Link className="text-primary hover:underline" href={`/documents/${document.id}`}>{document.name}</Link></CardTitle></CardHeader><CardContent><p className="text-sm">{documentCategoryLabels[document.category as keyof typeof documentCategoryLabels]} · {documentStatusLabels[document.status as keyof typeof documentStatusLabels]}</p><p className="mt-1 text-sm text-muted-foreground">Version {document.current_version_number}{document.expires_on ? ` · expire le ${document.expires_on}` : " · sans expiration"}</p></CardContent></Card></li>)}</ul> : <div className="rounded-xl border border-dashed p-10 text-center"><h2 className="text-lg font-semibold">Aucun document</h2><p className="mt-2 text-sm text-muted-foreground">Ajoutez un document ou adaptez les filtres.</p></div>}</main>;
}
function Filter({ name, label, value, options, all }: { name: string; label: string; value?: string; options: Array<{ value: string; label: string }>; all?: boolean }) { return <label className="text-sm font-medium">{label}<select name={name} defaultValue={value ?? ""} className="mt-2 h-11 w-full rounded-md border bg-background px-3">{all ? <option value="">Tous</option> : null}{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
