import { notFound } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace";
import { updateMissionAction } from "@/modules/missions/actions/mission.actions";
import { MissionForm } from "@/modules/missions/components/mission-form";
import { getMission } from "@/modules/missions/services/mission.service";
import { listOrganizations } from "@/modules/organizations/services/list-organizations";
import { listProjects } from "@/modules/projects/services/project.service";
export default async function EditMissionPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const workspace = await getActiveWorkspace(); const [mission, organizations, projects] = await Promise.all([getMission(workspace.id, id), listOrganizations(workspace.id), listProjects(workspace.id)]); if (!mission) notFound(); const options = organizations.map(({ id, name }) => ({ id, name })); if (mission.organization && !options.some((option) => option.id === mission.organization_id)) options.push({ id: mission.organization_id, name: `${mission.organization.name} (archivée)` }); const projectOptions = projects.map(({ id, name, organization_id }) => ({ id, name, organization_id })); if (mission.project && !projectOptions.some((option) => option.id === mission.project_id)) projectOptions.push({ id: mission.project.id, name: `${mission.project.name} (archivé)`, organization_id: mission.organization_id }); return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-3xl space-y-6 px-4 py-7 outline-none sm:px-6 sm:py-9"><h1 className="text-2xl font-semibold">Modifier la mission</h1><Card><CardHeader><CardTitle>Informations</CardTitle></CardHeader><CardContent><MissionForm action={updateMissionAction.bind(null, id)} mission={mission} organizations={options} projects={projectOptions} cancelHref={`/missions/${id}`} /></CardContent></Card></main>; }
