import assert from "node:assert/strict";
import test from "node:test";
import { createClient } from "@supabase/supabase-js";
import { createTestUser, getTestEnv } from "../helpers/node-test-client.mjs";

async function context(label) { const user = await createTestUser(label); const organization = await user.client.from("organizations").insert({ workspace_id: user.workspaceId, name: `Synthetic ${crypto.randomUUID()}`, type: "other" }).select("id").single(); assert.equal(organization.error, null); return { ...user, organizationId: organization.data.id }; }
async function pendingDocument(user, suffix = crypto.randomUUID()) { const document = await user.client.from("documents").insert({ workspace_id: user.workspaceId, organization_id: user.organizationId, name: `Synthetic document ${suffix}`, category: "administrative", status: "valid", issued_on: "2026-09-01", expires_on: "2026-09-30" }).select("id").single(); assert.equal(document.error, null); const session = await user.client.from("document_upload_sessions").insert({ workspace_id: user.workspaceId, document_id: document.data.id, storage_bucket: "synthetic-private-bucket", storage_key: `${user.workspaceId}/${document.data.id}/${crypto.randomUUID()}.pdf`, original_file_name: "synthetic.pdf", expected_size: 1024, expected_mime: "application/pdf", state: "verifying", expires_at: new Date(Date.now() + 60_000).toISOString() }).select("id").single(); assert.equal(session.error, null); return { documentId: document.data.id, sessionId: session.data.id }; }

test("documents and upload sessions deny anonymous and foreign workspaces", async () => { const { url, key } = getTestEnv(); const anonymous = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); for (const table of ["documents", "document_versions", "document_upload_sessions"]) assert.equal((await anonymous.from(table).select("*")).error?.code, "42501"); const [owner, outsider] = await Promise.all([context("documents-owner"), context("documents-outsider")]); const row = await pendingDocument(owner); assert.deepEqual((await outsider.client.from("documents").select("id").eq("id", row.documentId)).data, []); assert.deepEqual((await outsider.client.from("document_upload_sessions").select("id").eq("id", row.sessionId)).data, []); assert.deepEqual((await outsider.client.from("documents").update({ name: "Forbidden" }).eq("id", row.documentId).select("id")).data, []); assert.notEqual((await outsider.client.rpc("finalize_document_upload", { p_session_id: row.sessionId, p_actual_size: 1024, p_sha256: "a".repeat(64), p_etag: null })).error, null); });

test("finalization is atomic, immutable and idempotent", async () => { const owner = await context("documents-finalize"); const row = await pendingDocument(owner); const input = { p_session_id: row.sessionId, p_actual_size: 1024, p_sha256: "b".repeat(64), p_etag: "synthetic-etag" }; const first = await owner.client.rpc("finalize_document_upload", input); assert.equal(first.error, null); const second = await owner.client.rpc("finalize_document_upload", input); assert.equal(second.error, null); assert.equal(second.data, first.data); const versions = await owner.client.from("document_versions").select("id, version_number, sha256").eq("document_id", row.documentId); assert.equal(versions.error, null); assert.equal(versions.data.length, 1); assert.equal(versions.data[0].version_number, 1); assert.equal((await owner.client.from("documents").select("current_version_number").eq("id", row.documentId).single()).data.current_version_number, 1); assert.notEqual((await owner.client.from("document_versions").update({ sha256: "c".repeat(64) }).eq("id", first.data)).error, null); assert.notEqual((await owner.client.from("document_versions").delete().eq("id", first.data)).error, null); });

test("document constraints reject invalid dates, contexts and foreign-shaped object keys", async () => { const [owner, outsider] = await Promise.all([context("documents-constraints"), context("documents-context-outsider")]); assert.equal((await owner.client.from("documents").insert({ workspace_id: owner.workspaceId, name: "Bad dates", category: "other", status: "draft", issued_on: "2026-09-10", expires_on: "2026-09-01" })).error?.code, "23514"); assert.notEqual((await owner.client.from("documents").insert({ workspace_id: owner.workspaceId, organization_id: outsider.organizationId, name: "Bad context", category: "other", status: "draft" })).error, null); const document = await owner.client.from("documents").insert({ workspace_id: owner.workspaceId, name: "Storage scope", category: "other", status: "draft" }).select("id").single(); assert.equal(document.error, null); const foreignKey = `${outsider.workspaceId}/${document.data.id}/${crypto.randomUUID()}.pdf`; assert.equal((await owner.client.from("document_upload_sessions").insert({ workspace_id: owner.workspaceId, document_id: document.data.id, storage_bucket: "synthetic-private-bucket", storage_key: foreignKey, original_file_name: "synthetic.pdf", expected_size: 1, expected_mime: "application/pdf", expires_at: new Date(Date.now() + 60_000).toISOString() })).error?.code, "23514"); });
