import Link from "next/link";
import { notFound } from "next/navigation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace";
import { listMissions } from "@/modules/missions/services/mission.service";
import { archiveProjectAction } from "@/modules/projects/actions/project.actions";
import { projectStatusLabels } from "@/modules/projects/schemas/project.schema";
import { getProject } from "@/modules/projects/services/project.service";
export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const workspace = await getActiveWorkspace(); const [project, missions] = await Promise.all([getProject(workspace.id, id), listMissions(workspace.id, "active", undefined, undefined, id)]); if (!project) notFound(); return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-5xl space-y-6 px-4 py-7 outline-none sm:px-6 sm:py-9"><div><Link href="/projects" className="text-sm font-medium text-primary hover:underline">← Projets</Link><h1 className="mt-3 text-2xl font-semibold">{project.name}</h1><p className="mt-1 text-sm text-muted-foreground">{project.organization?.name} · {projectStatusLabels[project.status]}</p></div><Card><CardHeader><CardTitle>Informations</CardTitle></CardHeader><CardContent>{project.description ? <p className="whitespace-pre-wrap text-sm">{project.description}</p> : <p className="text-sm text-muted-foreground">Aucune description.</p>}<p className="mt-3 text-sm">Début : {project.starts_on ?? "Non défini"} · Cible : {project.target_ends_on ?? "Non définie"}</p></CardContent></Card><div className="flex flex-col gap-3 sm:flex-row"><Link href={`/projects/${id}/edit`} className={buttonVariants({ variant: "outline" })}>Modifier</Link>{!project.archived_at ? <form action={archiveProjectAction.bind(null, id)}><Button type="submit" variant="destructive" className="w-full">Archiver</Button></form> : null}</div><section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Missions</h2>{!project.archived_at ? <Link href={`/missions/new?project=${id}`} className={buttonVariants({ size: "sm" })}>Nouvelle mission</Link> : null}</div>{missions.length ? <ul className="space-y-3">{missions.map((mission) => <li key={mission.id} className="rounded-xl border bg-card p-4"><Link href={`/missions/${mission.id}`} className="font-semibold text-primary hover:underline">{mission.title}</Link></li>)}</ul> : <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Aucune mission liée.</div>}</section></main>; }
