import Link from "next/link";
import { notFound } from "next/navigation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace";
import { archiveDocumentAction } from "@/modules/documents/actions/document.actions";
import { documentCategoryLabels, documentStatusLabels } from "@/modules/documents/schemas/document.schema";
import { getDocument } from "@/modules/documents/services/document.service";

export default async function DocumentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const workspace = await getActiveWorkspace(); const document = await getDocument(workspace.id, id); if (!document) notFound();
  return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-4xl space-y-6 px-4 py-7 outline-none sm:px-6 sm:py-9"><div><Link href="/documents" className="text-sm font-medium text-primary hover:underline">← Documents</Link><h1 className="mt-3 text-2xl font-semibold">{document.name}</h1><p className="mt-1 text-sm text-muted-foreground">{documentCategoryLabels[document.category as keyof typeof documentCategoryLabels]} · {documentStatusLabels[document.status as keyof typeof documentStatusLabels]}</p></div><Card><CardHeader><CardTitle>Informations</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Émission : {document.issued_on ?? "Non définie"}</p><p>Expiration : {document.expires_on ?? "Non définie"}</p>{document.notes ? <p className="whitespace-pre-wrap">{document.notes}</p> : null}</CardContent></Card><div className="flex flex-col gap-3 sm:flex-row"><Link href={`/documents/${id}/edit`} className={buttonVariants({ variant: "outline" })}>Modifier</Link>{!document.archived_at ? <Link href={`/documents/${id}/replace`} className={buttonVariants()}>Ajouter une version</Link> : null}{!document.archived_at ? <form action={archiveDocumentAction.bind(null, id)}><Button type="submit" variant="destructive" className="w-full">Archiver</Button></form> : null}</div><section className="space-y-4"><h2 className="text-xl font-semibold">Historique des versions</h2><ul className="space-y-3">{document.versions.map((version) => <li key={version.id} className="flex flex-col gap-3 rounded-xl border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">Version {version.version_number} · {version.original_file_name}</p><p className="break-all text-xs text-muted-foreground">{Number(version.size_bytes).toLocaleString("fr-FR")} octets · SHA-256 {version.sha256}</p></div><a href={`/api/documents/${id}/versions/${version.id}/download`} className={buttonVariants({ variant: "outline", size: "sm" })}>Télécharger</a></li>)}</ul></section></main>;
}
