import Link from "next/link";
import { notFound } from "next/navigation";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getActiveWorkspace } from "@/lib/auth/get-active-workspace";
import { archiveTaskAction } from "@/modules/tasks/actions/task.actions";
import { TaskBoard } from "@/modules/tasks/components/task-board";
import { isTaskOverdue, taskPriorityLabels, taskStatusLabels } from "@/modules/tasks/schemas/task.schema";
import { getTask, listTasks } from "@/modules/tasks/services/task.service";
export default async function TaskDetailPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const workspace = await getActiveWorkspace(); const task = await getTask(workspace.id, id); if (!task) notFound(); const missionTasks = await listTasks(workspace.id, { missionId: task.mission_id }); const subtasks = missionTasks.filter((candidate) => candidate.parent_task_id === id); const archive = archiveTaskAction.bind(null, id); const today = new Date().toISOString().slice(0, 10); return <main id="main-content" tabIndex={-1} className="mx-auto w-full max-w-4xl space-y-6 px-4 py-7 outline-none sm:px-6 sm:py-9"><div><Link href="/tasks" className="text-sm font-medium text-primary hover:underline">← Tâches</Link><h1 className="mt-3 text-2xl font-semibold">{task.title}</h1><p className="mt-1 text-sm text-muted-foreground">{task.mission?.title} · {taskStatusLabels[task.status]}</p></div><Card><CardHeader><CardTitle>Informations</CardTitle></CardHeader><CardContent>{task.description ? <p className="whitespace-pre-wrap text-sm">{task.description}</p> : <p className="text-sm text-muted-foreground">Aucune description.</p>}<p className="text-sm">Priorité : {taskPriorityLabels[task.priority]} · Échéance : {task.due_on ?? "Non définie"}</p>{isTaskOverdue(task, today) ? <p className="font-medium text-destructive">Cette tâche est en retard.</p> : null}</CardContent></Card><div className="flex flex-col gap-3 sm:flex-row"><Link href={`/tasks/${id}/edit`} className={buttonVariants({ variant: "outline" })}>Modifier</Link>{!task.parent_task_id && !task.archived_at ? <Link href={`/tasks/new?mission=${task.mission_id}&parent=${id}`} className={buttonVariants({ variant: "outline" })}>Ajouter une sous-tâche</Link> : null}{!task.archived_at ? <form action={archive}><Button type="submit" variant="destructive" className="w-full">Archiver</Button></form> : null}</div>{!task.parent_task_id ? <section className="space-y-4"><h2 className="text-xl font-semibold">Sous-tâches</h2><TaskBoard tasks={subtasks} /></section> : null}</main>; }
