import { documentCategories, documentCategoryLabels, documentStatuses, documentStatusLabels, type DocumentMetadata } from "../schemas/document.schema";

export type DocumentContextOptions = { organizations: Array<{ id: string; name: string }>; projects: Array<{ id: string; name: string }>; missions: Array<{ id: string; title: string }> };
const control = "mt-2 h-11 w-full rounded-md border bg-background px-3 outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2";
export function DocumentFields({ document, contexts, errors = {} }: { document?: Partial<DocumentMetadata>; contexts: DocumentContextOptions; errors?: Record<string, string[] | undefined> }) {
  return <div className="space-y-5">
    <Field label="Nom" name="name" value={document?.name ?? ""} required error={errors.name?.[0]} />
    <div className="grid gap-4 sm:grid-cols-2"><Select label="Catégorie" name="category" value={document?.category ?? "administrative"} options={documentCategories.map((value) => ({ value, label: documentCategoryLabels[value] }))} /><Select label="Statut" name="status" value={document?.status ?? "draft"} options={documentStatuses.map((value) => ({ value, label: documentStatusLabels[value] }))} /></div>
    <div className="grid gap-4 sm:grid-cols-3"><Select label="Organisation (facultatif)" name="organization_id" value={document?.organization_id ?? ""} options={contexts.organizations.map((item) => ({ value: item.id, label: item.name }))} empty /><Select label="Projet (facultatif)" name="project_id" value={document?.project_id ?? ""} options={contexts.projects.map((item) => ({ value: item.id, label: item.name }))} empty /><Select label="Mission (facultatif)" name="mission_id" value={document?.mission_id ?? ""} options={contexts.missions.map((item) => ({ value: item.id, label: item.title }))} empty /></div>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="Date d’émission" name="issued_on" type="date" value={document?.issued_on ?? ""} /><Field label="Date d’expiration" name="expires_on" type="date" value={document?.expires_on ?? ""} error={errors.expires_on?.[0]} /></div>
    <label className="block text-sm font-medium">Notes<textarea name="notes" defaultValue={document?.notes ?? ""} maxLength={2000} rows={4} className="mt-2 w-full rounded-md border bg-background px-3 py-2 outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" /></label>
  </div>;
}
function Field({ label, name, value, type = "text", required, error }: { label: string; name: string; value: string; type?: string; required?: boolean; error?: string }) { const id = `document-${name}`; return <label htmlFor={id} className="block text-sm font-medium">{label}<input id={id} name={name} type={type} defaultValue={value} required={required} className={control} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} />{error ? <span id={`${id}-error`} className="mt-1 block text-sm text-destructive">{error}</span> : null}</label>; }
function Select({ label, name, value, options, empty }: { label: string; name: string; value: string; options: Array<{ value: string; label: string }>; empty?: boolean }) { return <label className="block text-sm font-medium">{label}<select name={name} defaultValue={value} className={control}>{empty ? <option value="">Aucun</option> : null}{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
